apiVersion: v2
appVersion: "20220121"
icon: https://photoprism.app/static/icons/logo.svg
description: AI-powered app for browsing, organizing & sharing your photo collection.
name: photoprism
version: 1.0.4
dependencies:
- name: common
  repository: file://../../../library/common/2206.0.0
  version: 2206.0.0
home: https://photoprism.app/
keywords:
- media
