apiVersion: v2
appVersion: "2.0.1"
icon: http://www.diskoverdata.com/wp-content/uploads/2019/09/diskover.png
description: Diskover is used to monitor size/volumes of distributed dataset.
name: diskoverdata
version: 1.0.3
dependencies:
- name: common
  repository: file://../../../library/common/2206.0.0
  version: 2206.0.0
home: https://github.com/diskoverdata/diskover-community/
keywords:
- storage
- monitoring
- management
sources:
- https://github.com/diskoverdata/diskover-community/
