image:
  pullPolicy: IfNotPresent
  repository: linuxserver/diskover
  tag: "2.0.1"

elasticsearch:
  image:
    pullPolicy: IfNotPresent
    repository: docker.elastic.co/elasticsearch/elasticsearch
    tag: "7.5.2"

python:
  image:
    pullPolicy: IfNotPresent
    repository: python
    tag: "3.10"

environmentVariables: []
extraAppVolumeMounts: []
extraDataVolumeMounts: []
web_port: 32000
dnsConfig:
  options: []
emptyDirVolumes: true
appVolumeMounts:
  config:
    emptyDir: true
    mountPath: /config
  data:
    emptyDir: true
    mountPath: /data
elasticSearchAppVolumeMounts:
  esdata:
    emptyDir: true
    mountPath: /usr/share/elasticsearch/data

ownerUID: 568
ownerGID: 568
username: "admin"
password: "admin"
host: "192.169.0.156"
hostNetwork: false
timezone: "America/Los_Angeles"

diskoverCredentials:
  username: admin
  password: admin

cronjobSchedule: "0 3 * * *"
es_user: elasticsearch
